# This is the Snakemake configuration file that specifies paths and 
# and options for the snakemake pipeline.
# Anybody wishing to use the provided snakemake pipeline should first
# fill out this file with paths to their own data, as the Snakefile requires it.
# Every config option has reasonable defaults unless it is labeled as "required."
# All paths are relative to the directory that Snakemake is executed in.
# Note: this file is written in the YAML syntax (https://learnxinyminutes.com/docs/yaml/)

# The input data: reads, barcodes, and VCF ID for every sample
# required!
data:
  Rat_Amygdala_787A:
    reads: data/snRNA/Rat_Amygdala_787A_all_seq/outs/possorted_genome_bam.bam
    barcodes: data/snRNA/Rat_Amygdala_787A_all_seq/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
    vcf_id: 933000320046549
  Rat_Opioid_HS_1:
    reads: data/snRNA/Rat_Opioid_HS_1_premrna/outs/possorted_genome_bam.bam
    barcodes: data/snRNA/Rat_Opioid_HS_1_premrna/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
    vcf_id: 933000120138414
  Rat_Opioid_HS_2:
    reads: data/snRNA/Rat_Opioid_HS_2_premrna/outs/possorted_genome_bam.bam
    barcodes: data/snRNA/Rat_Opioid_HS_2_premrna/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
    vcf_id: 933000120138730
  Rat_Opioid_HS_3:
    reads: data/snRNA/Rat_Opioid_HS_3_premrna/outs/possorted_genome_bam.bam
    barcodes: data/snRNA/Rat_Opioid_HS_3_premrna/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
    vcf_id: 933000320045746
  Rat_Opioid_HS_4:
    reads: data/snRNA/Rat_Opioid_HS_4_premrna/outs/possorted_genome_bam.bam
    barcodes: data/snRNA/Rat_Opioid_HS_4_premrna/outs/filtered_feature_bc_matrix/barcodes.tsv.gz
    vcf_id: 933000320046622

# Which samples from the data should we use?
# This should be a subset of the samples in "data" above
# If this line is commented out or the list is empty, all samples will be used.
samples: [Rat_Opioid_HS_1]

# A VCF containing genotypes for every sample
# required!
vcf: data/vcf/HS_n10_telese_rename.vcf.gz

# The doublet rate for this simulation
# Defaults to 0.3 if not provided
rate: 0.3

# Path to the directory in which to place output files
# It will be created if it doesn't already exist
# If this value is not provided, it will default to "out"
out: out
